// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-ddd/src/application/users"
	users2 "go-ddd/src/domain/models/users"
	"go-ddd/src/infrastructure/repositories"
	"gorm.io/gorm"
)

// Injectors from user_wire.go:

func InitializeUserRegisterService(db *gorm.DB) *users.UserRegisterService {
	iUserRepository := repositories.NewUserRepository(db)
	userService := users2.NewUserService(iUserRepository)
	userRegisterService := users.NewUserRegisterService(iUserRepository, userService)
	return userRegisterService
}

func InitializeUserDeleteService(db *gorm.DB) *users.UserDeleteService {
	iUserRepository := repositories.NewUserRepository(db)
	userDeleteService := users.NewUserDeleteService(iUserRepository)
	return userDeleteService
}
